[package]
name = "TimmyKwesiCoin"
version = "0.0.0"

[addresses]
NamedAddr = "0xCAFE"

[dependencies]
MoveStdlib = { local = "/workspace/StackUp-Move/StackUp_Move_Campaign/move/language/move-stdlib", addr_subst = { "std" = "0x1" } }